---
- name: Install baseline system packages
  hosts: all
  become: yes

  vars:
    packages:
      - curl
      - git
      - htop
      - vim

  tasks:

    - name: Install required packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
